/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program.kelola.tv.kabel;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Rex1054
 */
public class inputUser extends javax.swing.JPanel {
int id = 0;
    /**
     * Creates new form inputUser
     */
    public inputUser() {
        initComponents();
        
        // ambil id terbaru dari database
        try {
            String sqls = "select * from pelanggan order by idPelanggan desc limit 1";
            java.sql.Connection conn = (Connection) konek.configDB();
            java.sql.Statement pst = conn.createStatement();
            ResultSet rs = pst.executeQuery(sqls);
            if (rs.next()) {
                id = rs.getInt("idPelanggan");
                id += 1;
                idPelanggan.setText(String.valueOf(id));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        
        // import data combobox kota
        try {
            String sqls = "select * from kota";
            java.sql.Connection conn = (Connection) konek.configDB();
            java.sql.Statement pst = conn.createStatement();
            ResultSet rs = pst.executeQuery(sqls);

            while (rs.next()) {
                kota.addItem(rs.getString("namaKota"));
            }

            rs.last();
            int jumlahdata = rs.getRow();
            rs.first();

        } catch (SQLException e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kelamin = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Depan = new javax.swing.JTextField();
        Belakang = new javax.swing.JTextField();
        laki = new javax.swing.JRadioButton();
        perem = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        kota = new javax.swing.JComboBox<>();
        desa = new javax.swing.JComboBox<>();
        telepon = new javax.swing.JTextField();
        jumlahTv = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        simpan = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        idPelanggan = new javax.swing.JTextField();
        cekKota = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setText("PELANGGAN BARU");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel2.setText("Nama Depan");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 47, -1, -1));

        jLabel3.setText("Nama Belakang");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 72, -1, -1));

        jLabel4.setText("Jenis Kelamin");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 95, -1, -1));
        add(Depan, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 45, 163, -1));
        add(Belakang, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 70, 160, -1));

        kelamin.add(laki);
        laki.setText("Laki-laki");
        add(laki, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 91, -1, -1));

        kelamin.add(perem);
        perem.setText("Perempuan");
        add(perem, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 91, -1, -1));

        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 116, -1, -1));

        kota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Kota"}));
        add(kota, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 200, -1, -1));

        desa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Desa"}));
        add(desa, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 230, -1, -1));
        add(telepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 260, 112, -1));
        add(jumlahTv, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 285, 70, -1));

        jLabel5.setText("Alamat");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 116, -1, -1));

        jLabel6.setText("Kota");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 205, -1, -1));

        jLabel7.setText("Desa");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 235, -1, -1));

        jLabel8.setText("No. HP / Telp.");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 262, -1, 17));

        jLabel9.setText("Jumlah Tv");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 287, -1, -1));

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 322, -1, -1));

        jLabel10.setText("ID Pelanggan");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));
        add(idPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 80, -1));

        cekKota.setText("Cek Kota");
        cekKota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekKotaActionPerformed(evt);
            }
        });
        add(cekKota, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        jLabel11.setText("*ID Pelanggan jangan diubah!!!");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // Tombol Simpan
        
        // cek kota dan desa
        String des = (String) desa.getSelectedItem();
        String kot = (String) kota.getSelectedItem();
        
        // cek nama depan dan belakang
        String nDepan = Depan.getText();
        String nBelakang =Belakang.getText();
        if (Depan.equals("")) {
            JOptionPane.showMessageDialog(null, "Nama Depan Belum diisi");
            Depan.requestFocus();
        } else if (Belakang.equals("")) {
            JOptionPane.showMessageDialog(null, "Nama Belakang Belum diisi");
            Belakang.requestFocus();
        } else {
            char [] huruf = nDepan.toCharArray();
            for (int i = 0; i < huruf.length; i++) {
                if (huruf[i] == ' ') {
                    JOptionPane.showMessageDialog(null, "Nama depan Mengandung spasi (' ')");
                    Depan.requestFocus();
                    break;
                } else if (huruf[i] == '1' || huruf[i] == '2' || huruf[i] == '3' || huruf[i] == '4'
                        || huruf[i] == '5' || huruf[i] == '6' || huruf[i] == '7' || huruf[i] == '8'
                        || huruf[i] == '9' || huruf[i] == '0'
                        ){
                    JOptionPane.showMessageDialog(null, "Nama depan Mengandung angka");
                    Depan.requestFocus();
                    break;
                }
            }
            char[] huruf2 = nBelakang.toCharArray();
            for (int i = 0; i < huruf2.length; i++) {
                if (huruf2[i] == ' ') {
                    JOptionPane.showMessageDialog(null, "Nama belakang Mengandung spasi (' ')");
                    Belakang.requestFocus();
                    break;
                } else if (huruf2[i] == '1' || huruf2[i] == '2' || huruf2[i] == '3' || huruf2[i] == '4'
                        || huruf2[i] == '5' || huruf2[i] == '6' || huruf2[i] == '7' || huruf2[i] == '8'
                        || huruf2[i] == '9' || huruf2[i] == '0'
                        ){
                    JOptionPane.showMessageDialog(null, "Nama belakang Mengandung angka");
                    Belakang.requestFocus();
                    break;
                }
            }
        }
        
        // cek jenis kelamin
        String jKelamin = "";
        if (laki.isSelected()) {
            jKelamin = "laki-laki";
        } else if (perem.isSelected()) {
            jKelamin = "perempuan";
        } else {
            JOptionPane.showMessageDialog(null, "Jenis Kelamin Belum Dipilih");
            laki.requestFocus();
        }
        // 
        
        // cek alamat
        String alm = alamat.getText();
        if (alm.equals("")) {
            JOptionPane.showMessageDialog(null, "Alamat kosong");
            alamat.requestFocus();
        }
        
        // cek kota dan desa
        String k = (String) kota.getSelectedItem();
        String d = (String) desa.getSelectedItem();
        if (k.equalsIgnoreCase("Kota") || d.equalsIgnoreCase("Desa")) {
            JOptionPane.showMessageDialog(null, "Kota atau Desa salah");
        }
        
        // nomor hp / telepon
        String no = telepon.getText();
        char[] nom = no.toCharArray();
        for (int i = 0; i < nom.length; i++) {
            if (nom[i] != 1 || nom[i] != 2 || nom[i] != 3 || nom[i] != 4
                        || nom[i] != 5 || nom[i] != 6 || nom[i] != 7 || nom[i] != 8
                        || nom[i] != 9 || nom[i] != 0
                        ){
                    JOptionPane.showMessageDialog(null, "Nomor salah, silahkan cek!");
                    telepon.requestFocus();
                    break;
                }
        }
        
        // cek jumlah tv
        String tv = jumlahTv.getText();
        char[] tvs = tv.toCharArray();
            if (tv.equals("")) {
                JOptionPane.showMessageDialog(null, "Jumlah tidak boleh kosong!");
                jumlahTv.requestFocus();
                
            } else {
        for (int i = 0; i < tvs.length; i++) {
            if (tvs[i] != 1 || tvs[i] != 2 || tvs[i] != 3 || tvs[i] != 4
                        || tvs[i] != 5 || tvs[i] != 6 || tvs[i] != 7 || tvs[i] != 8
                        || tvs[i] != 9 || tvs[i] != 0
                        ){
                    JOptionPane.showMessageDialog(null, "Jumlah salah, silahkan cek!\n"
                            + "(Jumlah tv antara 1 ~ 99)");
                    jumlahTv.requestFocus();
                    break;
                }
        }
        }

        // simpan
        try {
            String sqls = "insert into pelanggan values (\n"
                    + "    '" + id + "','" + Depan.getText() + "','" + Belakang.getText() + "','" + jKelamin + "','" + alamat.getText() + "','"+des+"','"+kot+"','"+telepon.getText()+"','"+jumlahTv.getText()+"'\n"
                    + "    )";
            java.sql.Connection conn = (Connection) konek.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sqls);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Input Data berhasil!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void cekKotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekKotaActionPerformed
        // Import data combo box Desa
        String kt = String.valueOf(kota.getSelectedItem());
        int idKota = 0;
        // mengambil idKota
        try {
            String sqls = "select * from kota";
            java.sql.Connection conn = (Connection) konek.configDB();
            java.sql.Statement pst = conn.createStatement();
            ResultSet rs = pst.executeQuery(sqls);
            while (rs.next()) {
                if (kt.equals(rs.getString("namaKota"))) {
                    idKota = rs.getInt("idKota");

                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        // import data combobox desa sesuai data combobox kota
        try {
            desa.removeAllItems();

            String sqls = "select * from desa where idKota = " + idKota;
            java.sql.Connection conn = (Connection) konek.configDB();
            java.sql.Statement pst = conn.createStatement();
            ResultSet rs = pst.executeQuery(sqls);
            while (rs.next()) {
                desa.addItem(rs.getString("namaDesa"));
            }

            rs.last();
            int jumlahdata = rs.getRow();
            rs.first();

        } catch (SQLException e) {
        }
    }//GEN-LAST:event_cekKotaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Belakang;
    private javax.swing.JTextField Depan;
    private javax.swing.JTextArea alamat;
    private javax.swing.JButton cekKota;
    private javax.swing.JComboBox<String> desa;
    private javax.swing.JTextField idPelanggan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlahTv;
    private javax.swing.ButtonGroup kelamin;
    private javax.swing.JComboBox<String> kota;
    private javax.swing.JRadioButton laki;
    private javax.swing.JRadioButton perem;
    private javax.swing.JButton simpan;
    private javax.swing.JTextField telepon;
    // End of variables declaration//GEN-END:variables
}
