/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program.kelola.tv.kabel;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
/**
 *
 * @author Rex1054
 */
public class lihatUser extends javax.swing.JPanel {

    /**
     * Creates new form lihatUser
     */
    public lihatUser() {
        initComponents();
        DefaultTableModel model = new DefaultTableModel ( );
        model.getDataVector( ).removeAllElements( );
        model.fireTableDataChanged( );
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);

     try{
           //membuat statemen pemanggilan data pada table tblGaji dari database
           java.sql.Connection conn = (Connection) konek.configDB();
            java.sql.Statement pst = conn.createStatement();
           String sql        = "Select * from pelanggan";
           ResultSet res   = pst.executeQuery(sql);

           //penelusuran baris pada tabel tblGaji dari database
           while(res.next ()){
                String[ ] obj = new String[9];
                obj[0] = res.getString("idPelanggan"); 
                obj[1] = res.getString("nDepan");
                obj[2] = res.getString("nBelakang"); 
                obj[3] = res.getString("jenisKelamin");
                obj[4] = res.getString("alamat"); 
                obj[5] = res.getString("desa");
                obj[6] = res.getString("kota");
                obj[7] = res.getString("noHP");
                obj[8] = res.getString("jumlahTV");

                dtm.addRow(obj);
            }
      }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage() );
      }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setText("DAFTAR PELANGGAN");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Pelanggan", "Nama Depan", "Nama Belakang", "Jenis Kelamin", "Alamat", "Desa", "Kota", "No. Telepon", "Jumlah TV"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 500, 230));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
